spring:
  application:
    name: chat

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

  jackson:
    time-zone: Asia/Seoul


  kafka:
    bootstrap-servers: flowchat.shop:30010 # Kubernetes Kafka ??? ??? ??
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


  datasource:
    url: jdbc:mariadb://localhost:3308/chat # ?? ??? ??? DB URL
    username: chat # ?? ??? ??? DB ??? ??
    password: qwer1234 # ?? ??? ??? DB ????
    driver-class-name: org.mariadb.jdbc.Driver

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY} # AWS S3 Access Key
      secret-key: ${S3_SECRET_KEY} # AWS S3 Secret Key
    region:
      static: ap-northeast-2 # AWS ?? ??
    s3:
      bucket: ${S3_BUCKET}


tag:
  version: 0.2.0

feign:
  client:
    name: member
    url: http://flowchat.shop:30002 # Feign ????? URL

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG  # OpenFeign ?? ??? ?? ???
    feign: DEBUG                               # Feign Client ??/?? ??? ?? ???
    org.springframework: WARN                 # Spring Framework ???? ??? ?? ???
    org.springframework.web: WARN             # Spring Web ?? ??? ?? ???
    org.springframework.security: WARN        # Spring Security ?? ??? ?? ???
    org.springframework.messaging.simp: DEBUG
    org.springframework.web.socket: DEBUG

server:
  port: 8089
  servlet:
    session:
      timeout: 60m

